### ISSUE TITLE
Did you get static linking working with cabal?

### ISSUE THREAD

**Issue by m-col** [4e6/text-icu-static-example#1]
Hi there. Firstly, thank you for writing up your findings when you were having trouble with this.

I came across this same issue, and I was wondering if any further progress had been made in the couple of years since. Specifically, I am trying to build a cabal/stack project, which your readme suggests would succeed if I had a greater degree of control over the order of options passed to the compiler. Did you ever discover a way to do this? Or perhaps a workaround that is more convenient than taking manual control of the compiler invokation?

**Comment by 4e6** [comment]
Sorry, can't help you with this. I don't remember doing anything beyond this write-up.

**Comment by m-col** [comment]
No worries, thanks again!
